version: '3.6' 
services: 
  app: 
    image: alexisfr/flask-app:latest 
    depends_on: 
      - db 
    environment: 
      - REDIS_HOST=db 
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
  db:
    image: redis:alpine
    volumes:
      - /home/agus/Documents/facultad/cursada_2022/ing-sw-3/practico/ing-sw-3/trabajo-practico-03/redis_data:/data
